---
title: "Union of BibTeX Files"
date: "`r format(Sys.Date())`"
output: html_document
---

Overview

Create a union `.bib` by collecting all entries from a source directory into a single target file.

Setup

```{r}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
source("https://raw.githubusercontent.com/eogasawara/mylibrary/refs/heads/main/references/ref_utils.R")
# As duas linhas abaixo sao apenas para o cenario de teste desta documentacao.
# Em uso real, basta remover esse bloco e configurar corretamente as variaveis
# de entrada para apontarem para os seus arquivos reais.
source("https://raw.githubusercontent.com/eogasawara/mylibrary/refs/heads/main/references/reference_examples_setup.R")
download_reference_example_files()
```

Inputs

```{r}
source_dir <- "union_source" # diretorio com arquivos .bib no diretorio atual
target_bib <- "union_output.bib" # arquivo .bib de saida no diretorio atual
```

Build Union

```{r}
unionBibs(source_dir, target_bib)
cat("Union written to:", target_bib, "\n")
```

